### ISSUE TITLE
JaPS Integration

### ISSUE THREAD

**Issue by MarvinErkes** [JackWhite20/Cobra#1]
How can I use JaPS PubSubCache in this project?
I dont get it working, because it works with consumers.

**Comment by JackWhite20** [comment]
How do you want to use the cache here?

**Comment by MarvinErkes** [comment]
http://hastebin.com/yozonohami.vbs

**Comment by JackWhite20** [comment]
If you want it to work for now, you can use a CountDownLatch like this:

http://hastebin.com/uqaqaheduv.java

Keep in mind that the await call will be blocked, so it would make sense to put the uuid syntax error to the top as default, and then let the await call have a timeout like this:

```java
countDownLatch.await(2, TimeUnit.SECONDS);
```
Maybe you need to adjust the value.

**Comment by MarvinErkes** [comment]
Thanks. And the second thing is that there comes a error in the console if the argument is not given in the url.

**Comment by JackWhite20** [comment]
No problem.
What did you expect instead? Normally you check the URL before you call, or Do you want the Argument empty then?

**Comment by MarvinErkes** [comment]
yeah it can be null then

**Comment by MarvinErkes** [comment]
and eventually a solution for showing something if a path not exists

**Comment by JackWhite20** [comment]
Can you please hastebin such an exception?

It should normally return the status type NOT_FOUND if you try to reach an invalid path.

**Comment by MarvinErkes** [comment]
There is only exception if the argument is not set. No there is only a blank screen if the path not exists

**Comment by JackWhite20** [comment]
Yes, and it would be easier for me to identify the problem if i can see such an exception.

Yes, because it's not HTML, but the response status. You can view it with F12 under Network in Firefox for example.

**Comment by MarvinErkes** [comment]
Oh ok. Then sorry, but can you do, that there not comes an exception when the argument is not given in the URL? Error: http://hastebin.com/iconovapon.vbs

**Comment by JackWhite20** [comment]
Here you go, the param value is now null if no param is specified:

[cobra-server-2.0.1.zip](https://github.com/JackWhite20/Cobra/files/512136/cobra-server-2.0.1.zip)

The official release will come tomorrow.

**Comment by MarvinErkes** [comment]
Thanks :)

**Comment by JackWhite20** [comment]
No problem, if you have any further trouble just create a new issue :)
