### ISSUE TITLE
Upload to MavenCentral or other repo

### ISSUE THREAD

**Issue by BrainStone** [JackWhite20/Cobra#2]
Hi. Would it be possible for you to upload this to MavenCentral or another maven repository so it doesn't have to be built locally?

**Comment by JackWhite20** [comment]
Hey,

yes, i am currently setting up a public nexus repository for all of my projects, including Cobra.

**Comment by JackWhite20** [comment]
Quick update:

If everything goes well, it should be up later today (posible in the evening).

**Comment by JackWhite20** [comment]
Everything is working and up, currently waiting for the Domain to use the correct nameservers. I hope that this and the DNS name updates are finished in the evening.

**Comment by BrainStone** [comment]
From experience it takes about 1-2 hours.

**Comment by JackWhite20** [comment]
Hey, good news, it is finish configured and ready to use.

It would be cool if you can test it and tell me if it works for you too:

    <repositories>
        <repository>
            <id>jackwhite20</id>
            <url>https://repo.jackwhite20.net/repository/maven-snapshots/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>de.jackwhite20</groupId>
            <artifactId>cobra-client</artifactId>
            <version>2.1.2-SNAPSHOT</version>
        </dependency>
    </dependencies>

The "Download Documention" feature with maven should theoretically also work.

**Comment by BrainStone** [comment]
@JackWhite20 The repo is working. But why version 2.1.2? I thought you were on 2.2.2?

**Comment by BrainStone** [comment]
But the dependencies seem to be wrong. As neither the client nor the server depend on cobra-shared

**Comment by JackWhite20** [comment]
Yes, but that is the snapshot version and not the release version that is coming.

The cobra-shared packages are in the client and server jar as you can see [here](https://img.jackwhite20.net/images/l11fy11jg11w)

**Comment by BrainStone** [comment]
Ok. Still, I wouldn't shade them and instead just depend on them. Prevents duplicate code when using both.

**Comment by JackWhite20** [comment]
That shouldn't be a problem as long as you are using the same version.

**Comment by BrainStone** [comment]
Still wouldn't do it.

**Comment by JackWhite20** [comment]
Hey, could you please try this release version?

This version comes with the latest commits (eg. the request body as raw bytes). Note that the repo now ends with ".../maven-releases/" and the artifact versions with "..-RELEASE".

    <repositories>
        <repository>
            <id>jackwhite20</id>
            <url>https://repo.jackwhite20.net/repository/maven-releases/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>de.jackwhite20</groupId>
            <artifactId>cobra-client</artifactId>
            <version>2.3.2-RELEASE</version>
        </dependency>
        <dependency>
            <groupId>de.jackwhite20</groupId>
            <artifactId>cobra-server</artifactId>
            <version>2.3.2-RELEASE</version>
        </dependency>
    </dependencies>

**Comment by JackWhite20** [comment]
Hey, no problem. Nice to hear that everything is working!
