### ISSUE TITLE
Allow access to body

### ISSUE THREAD

**Issue by BrainStone** [JackWhite20/Cobra#4]
It is possible that a post request doesn't contain a form but rather just a raw body. It would be useful if that could be accessed.

Maybe even if the data is form data.

**Comment by JackWhite20** [comment]
Actually there are two methods in the Body class to get the content as a string or as raw bytes.

"Body.content()" and "Body.bytes()".

**Comment by BrainStone** [comment]
I meant in the server and the request body.

**Comment by JackWhite20** [comment]
So adding the same methods as above, but in the `Request` class?

**Comment by BrainStone** [comment]
Would be very apprechiated. In fact with the current implementation it is impossible for me to get the data if a client sends a file or JSON data, etc.  
You should be able to detect if there is post data by inspecting the Content-Type header.

**Comment by BrainStone** [comment]
Any updates on this?

**Comment by JackWhite20** [comment]
Hey, yes.

I will rewrite the reading part to be at the byte level, so i can access the body data as bytes too.

**Comment by BrainStone** [comment]
Good. Can you estimate when this will be available? It’s blocking my project :/

**Comment by JackWhite20** [comment]
Oh okay, yea, I will try to finish it today.
