### ISSUE TITLE
Expose views of header and post data maps

### ISSUE THREAD

**Issue by BrainStone** [JackWhite20/Cobra#5]
Being able to read specific headers or post data fields is nice but sometimes you just need to iterate over all headers and post fields. So exposing the maps through something like: `Collections.unmodifiableMap(headers)` could very useful. (This makes sure the map itself can't be modified.)

**Comment by JackWhite20** [comment]
There is `Headers.headers()`, not unmodifiable, because after the response you can't get unexpected behaviour when changing the original map.

**Comment by BrainStone** [comment]
Talking about the Request class in the server.

**Comment by JackWhite20** [comment]
Was added with https://github.com/JackWhite20/Cobra/commit/3e5436c4c950e311754a3a71a486151c2b4272d3.
