### ISSUE TITLE
Consider using the very common getter and setter naming conventions

### ISSUE THREAD

**Issue by BrainStone** [JackWhite20/Cobra#7]
So I've noticed that your getters and setters never are named `getFoobar` or `setFoobar`, which is the almost the norm in Java. I think this would make the API a bit easier to use.

**Comment by JackWhite20** [comment]
I like the naming style of the getters and setters in this framework. Simple and short. Netty for example uses the same naming style for getters and setters.

**Comment by BrainStone** [comment]
I guess it's a matter of taste. But ok. It's up to you

**Comment by JackWhite20** [comment]
I have choosen it because how the config is made.

setHost("localhost");  
setPort(8080);  
setBacklog(25);

or

host("localhost");
port(8080);
backLog(25);

I think the second way is cleaner and nicer to read.

**Comment by BrainStone** [comment]
I think the first one is cleaner and better to read. Again, it's a matter of taste. I was just pointing out that the convention is to use set and get.

**Comment by JackWhite20** [comment]
As described in my comment above.
