### ISSUE TITLE
FilteredRequest should allow accessing the actual request

### ISSUE THREAD

**Issue by BrainStone** [JackWhite20/Cobra#8]
I some cases it is required to actually access all data from the actual request. You could expose the methods of the request through the delegate object (like you already do with some methods) or make a getter for it.

**Comment by JackWhite20** [comment]
What data exactly?

**Comment by BrainStone** [comment]
The actual request. Assuming you expose the headers and postData map, there would be certain data not directly accessible through the FilteredRequest.

**Comment by JackWhite20** [comment]
So just exposing `request()` from where all other data can be accessed? And adding `headers()` and `postData()` to the request class?

**Comment by BrainStone** [comment]
That would be perfect!

**Comment by JackWhite20** [comment]
Okay, I will look if I can add it later this day with the new release which is coming.
