### ISSUE TITLE
Client version being sent is wrong

### ISSUE THREAD

**Issue by BrainStone** [JackWhite20/Cobra#9]
The client currently sends the version Cobra v2.1.1. Should be v2.2.2 (or whatever version will be next)

(I hope you don't mind me opeing so many issues 😅 )

**Comment by JackWhite20** [comment]
Yeah, i have seen this while refactoring, it will be fixed with the new release coming tonight (with some other small improvements).

(That is okay i guess 😄)

**Comment by JackWhite20** [comment]
Fixed here https://github.com/JackWhite20/Cobra/commit/fa6dea032805f6ad0fd343aad625c92fb424b379.
